const menu = [
  {
    id: 1,
    title: "Fusulli Rotini",
    category: "Makarna",
    type: "Yiyecek",
    price: 14.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651068/menu-app/b4xnt9dnmnsqybdubfxo.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 2,
    title: "Lasagna",
    category: "Makarna",
    type: "Yiyecek",
    price: 14.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651069/menu-app/c82cjwshia8a0tsdqzsu.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 3,
    title: "Linguini",
    category: "Makarna",
    type: "Yiyecek",
    price: 14.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651069/menu-app/zmnirlxl6kr9usy5okfp.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 4,
    title: "Orecchiette",
    category: "Makarna",
    type: "Yiyecek",
    price: 14.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651069/menu-app/ofrhb6s8gsudsf9balcq.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 5,
    title: "Ravioli",
    category: "Makarna",
    type: "Yiyecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651069/menu-app/sqx7m8c9nhq2toqvjgyt.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 6,
    title: "Spaghetti",
    category: "Makarna",
    type: "Yiyecek",
    price: 16.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/c_limit,f_jpg,fl_lossy.any_format.preserve_transparency.progressive,h_1600,pg_1,q_auto,w_1600/v1/menu-app/xbyqtzufbip7uvnv1wpl",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 7,
    title: "Tortellini",
    category: "Makarna",
    type: "Yiyecek",
    price: 17.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/c_limit,f_jpg,fl_lossy.any_format.preserve_transparency.progressive,h_1600,pg_1,q_auto,w_1600/v1/menu-app/ggjqdmugwhmnk6ayribu",
    desc: `Red bean paste dessert, serving with honey.`,
  },

  {
    id: 8,
    title: "Farfalle",
    category: "Makarna",
    type: "Yiyecek",
    price: 14.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651068/menu-app/y0nax5ict97cbwcmpfdw.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 9,
    title: "Fettuccine",
    category: "Makarna",
    type: "Yiyecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651068/menu-app/kr9xcosrbzicnce3dahm.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 10,
    title: "Cheeseburger",
    category: "Burger",
    type: "Yiyecek",
    price: 13.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651067/menu-app/ym2nguvdifly3msyltpu.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 11,
    title: "Kiwi Burger",
    category: "Burger",
    type: "Yiyecek",
    price: 16.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651069/menu-app/a0n7fozbkgx6bnqzyt1x.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 12,
    title: "Fried Onion Burger",
    category: "Burger",
    type: "Yiyecek",
    price: 21.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651068/menu-app/ulavqylpki0epa8k3hc0.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 13,
    title: "Slider Burger",
    category: "Burger",
    type: "Yiyecek",
    price: 19.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/c_limit,f_jpg,fl_lossy.any_format.preserve_transparency.progressive,h_1600,pg_1,q_auto,w_1600/v1/menu-app/x2ib17evpshxveqgszbg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 14,
    title: "Pimento Cheeseburger",
    category: "Burger",
    type: "Yiyecek",
    price: 12.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651069/menu-app/oww6mvh2bdkzwq48yige.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 15,
    title: "Green Chile Cheeseburger",
    category: "Burger",
    type: "Yiyecek",
    price: 13.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651068/menu-app/mpzkk18rmg3emy9c5m7w.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 16,
    title: "Burrito",
    category: "Dürüm",
    type: "Yiyecek",
    price: 3.99,
    img: 'https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651067/menu-app/ayuz8id014n7qbsyfw6h.webp',
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 17,
    title: "Enchiladas",
    category: "Dürüm",
    type: "Yiyecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651067/menu-app/vzxj01qogopmqyospwx5.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 18,
    title: "Carna Asada Burrito",
    category: "Dürüm",
    type: "Yiyecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651067/menu-app/ch586st1crrcj36dbcja.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 19,
    title: "Latte",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651069/menu-app/llbqgsllfxqhudjyrpcf.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 20,
    title: "Macchiato",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651069/menu-app/txydvrit9hy4upwhb0yh.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 21,
    title: "Türk Kahvesi",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/c_limit,f_jpg,fl_lossy.any_format.preserve_transparency.progressive,h_1600,pg_1,q_auto,w_1600/v1/menu-app/eid7zj5vwnlar1wgrja4",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 22,
    title: "White Mocca",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/c_limit,f_jpg,fl_lossy.any_format.preserve_transparency.progressive,h_1600,pg_1,q_auto,w_1600/v1/menu-app/sdpitcmkwkj3uoyurceu",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 23,
    title: "White Chocolate Mocca",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/c_limit,f_jpg,fl_lossy.any_format.preserve_transparency.progressive,h_1600,pg_1,q_auto,w_1600/v1/menu-app/jmskx4tbaaclwn8hbom4",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 23,
    title: "Espresso",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651067/menu-app/vrmiklson7ic2vnp1vsw.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 24,
    title: "İce Latte",
    category: "Soguk",
    type: "İçecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651069/menu-app/p2npzvlm6flay1tyzmyq.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 25,
    title: "İce Americano",
    category: "Soguk",
    type: "İçecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651068/menu-app/eeaupyr38rwwbbebkbb6.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 26,
    title: "Karamel Frappe",
    category: "Frappe",
    type: "İçecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651069/menu-app/jwtndaqlsuhhj7a5u9wm.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 27,
    title: "Dondurmalı Frappe",
    category: "Frappe",
    type: "İçecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651067/menu-app/sknuzcd5uzdnza2tofyx.avif",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 28,
    title: "Oreo Frappe",
    category: "Frappe",
    type: "İçecek",
    price: 3.99,
    img: "https://res.cloudinary.com/dtar4nbiw/image/upload/v1679651069/menu-app/uuddnkau9tsuphtaqbhi.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  
];

export default menu;
