const menu = [
  {
    id: 1,
    title: "Fusulli Rotini",
    category: "Makarna",
    type: "Yiyecek",
    price: 14.99,
    img: "../menu-ımg/FusilliRotini.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 2,
    title: "Lasagna",
    category: "Makarna",
    type: "Yiyecek",
    price: 14.99,
    img: "../menu-ımg/Lasagna.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 3,
    title: "Linguini",
    category: "Makarna",
    type: "Yiyecek",
    price: 14.99,
    img: "../menu-ımg/Linguini.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 4,
    title: "Orecchiette",
    category: "Makarna",
    type: "Yiyecek",
    price: 14.99,
    img: "../menu-ımg/Orecchiette.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 5,
    title: "Ravioli",
    category: "Makarna",
    type: "Yiyecek",
    price: 3.99,
    img: "../menu-ımg/Ravioli.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 6,
    title: "Spaghetti",
    category: "Makarna",
    type: "Yiyecek",
    price: 16.99,
    img: "../menu-ımg/Spaghetti.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 7,
    title: "Tortellini",
    category: "Makarna",
    type: "Yiyecek",
    price: 17.99,
    img: "../menu-ımg/Tortellini.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },

  {
    id: 8,
    title: "Farfalle",
    category: "Makarna",
    type: "Yiyecek",
    price: 14.99,
    img: "../menu-ımg/farfalle.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 9,
    title: "Fettuccine",
    category: "Makarna",
    type: "Yiyecek",
    price: 3.99,
    img: "../menu-ımg/Fettuccine.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 10,
    title: "Cheeseburger",
    category: "Burger",
    type: "Yiyecek",
    price: 13.99,
    img: "../menu-ımg/cheeseburger.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 11,
    title: "Kiwi Burger",
    category: "Burger",
    type: "Yiyecek",
    price: 16.99,
    img: "../menu-ımg/kiwiburger.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 12,
    title: "Fried Onion Burger",
    category: "Burger",
    type: "Yiyecek",
    price: 21.99,
    img: "../menu-ımg/fried-onion-burgers.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 13,
    title: "Slider Burger",
    category: "Burger",
    type: "Yiyecek",
    price: 19.99,
    img: "../menu-ımg/slider-burger.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 14,
    title: "Pimento Cheeseburger",
    category: "Burger",
    type: "Yiyecek",
    price: 12.99,
    img: "../menu-ımg/pimento-cizburger.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 15,
    title: "Green Chile Cheeseburger",
    category: "Burger",
    type: "Yiyecek",
    price: 13.99,
    img: "../menu-ımg/greenburger.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 16,
    title: "Burrito",
    category: "Dürüm",
    type: "Yiyecek",
    price: 3.99,
    img: '../menu-ımg/burrito.jpeg',
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 17,
    title: "Enchiladas",
    category: "Dürüm",
    type: "Yiyecek",
    price: 3.99,
    img: "../menu-ımg/enchiladas-d.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 18,
    title: "Carna Asada Burrito",
    category: "Dürüm",
    type: "Yiyecek",
    price: 3.99,
    img: "../menu-ımg/carna.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 19,
    title: "Latte",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "../menu-ımg/latte.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 20,
    title: "Macchiato",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "../menu-ımg/macchiato.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 21,
    title: "Türk Kahvesi",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "../menu-ımg/türk-kahvesi.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 22,
    title: "White Mocca",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "../menu-ımg/white_mocca.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 23,
    title: "White Chocolate Mocca",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "../menu-ımg/white-c-mocca.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 23,
    title: "Espresso",
    category: "Sıcak",
    type: "İçecek",
    price: 3.99,
    img: "../menu-ımg/espresso.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 24,
    title: "İce Latte",
    category: "Soguk",
    type: "İçecek",
    price: 3.99,
    img: "../menu-ımg/ice-latte.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 25,
    title: "İce Americano",
    category: "Soguk",
    type: "İçecek",
    price: 3.99,
    img: "../menu-ımg/ice-americano.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 26,
    title: "Karamel Frappe",
    category: "Frappe",
    type: "İçecek",
    price: 3.99,
    img: "../menu-ımg/karamel-frappe.webp",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 27,
    title: "Dondurmalı Frappe",
    category: "Frappe",
    type: "İçecek",
    price: 3.99,
    img: "../menu-ımg/dondurmalı-frappe.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 28,
    title: "Oreo Frappe",
    category: "Frappe",
    type: "İçecek",
    price: 3.99,
    img: "../menu-ımg/oreo-frappe.jpeg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  
];

export default menu;
